### ISSUE TITLE
Publish Release Announce

### ISSUE THREAD

**Issue by go** [rancherjp/site#8]
Add Release Announce in Japanese for each released versions.

**Comment by FoxBoxsnet** [comment]
Page Create https://rancherjp.github.io/site/release-announce/

**Comment by go** [comment]
@ynott translated release announce for v1.2.0 and committed in 6304d158ff7d9a36e86e32ceb1e80e4094167025.

**Comment by FoxBoxsnet** [comment]
complete?

**Comment by go** [comment]
IMO, there are no problem to close this issue.
